all: Replace spaces with tabs

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -8,17 +8,17 @@
 # Configure the installation and root path.
 
 [ "$(basename $PWD)" = "scripts" ] && echo "Must be ran from the" \
-    "project root" && exit 1
+	"project root" && exit 1
 
 if [ ! -z "$1" ]; then
-    BIN="$1"
+	BIN="$1"
 else
-    BIN="$HOME/.local/bin"
-    SUDO=""
-    [ ! -d "$BIN" ] && BIN="$HOME/bin"
-    [ ! -d "$BIN" ] && BIN="/usr/local/bin" && SUDO="sudo"
-    [ ! -d "$BIN" ] && BIN="/usr/bin" && SUDO="sudo"
-    [ ! -d "$BIN" ] && echo "Could not find any destination" && exit 1
+	BIN="$HOME/.local/bin"
+	SUDO=""
+	[ ! -d "$BIN" ] && BIN="$HOME/bin"
+	[ ! -d "$BIN" ] && BIN="/usr/local/bin" && SUDO="sudo"
+	[ ! -d "$BIN" ] && BIN="/usr/bin" && SUDO="sudo"
+	[ ! -d "$BIN" ] && echo "Could not find any destination" && exit 1
 fi
 
 # Find all generated binaries and move them.
